### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by aguygarner** [hattori-lab/SACRA#6]
Hi, 
I am running Sacra on some reads corrected using NECAT. The output of NECAT makes the read names as follows with parentheses in them. 

ontsa_id_14509_(0_10814_10864_10814_109_22_0.000000)_(469_10822_10140_10864_57_51_46.646883):222-417

On the last step of running SACRA on this data I get the following error.
cns_final.fasta.blasttab.depth.pcratio.faidx.split10.sh: line 1: syntax error near unexpected token `('
cns_final.fasta.blasttab.depth.pcratio.faidx.split10.sh: line 1: `samtools faidx cns_final.fasta ontsa_id_14509_(0_10814_10864_10814_109_22_0.000000)_(469_10822_10140_10864_57_51_46.646883):222-417 >> cns_final.fasta.blasttab.depth.pcratio.faidx.split10.fasta'

Is there a simple work around to move forward with this or do I need to figure out how to change my read names?

**Comment by aguygarner** [comment]
it seems that single quotes in this command on line 148 of SACRA.sh resolves this issue
        echo "samtools faidx '$i' '$j' >> $n.fasta" >> $n.sh

**Comment by YuyaKiguchi** [comment]
Hi aguygarner,

Thank you for your information.
I think it's because samtools could not handle special characters like "(". Please remove "(" from the header of your fasta or add single quotes as you suggested.

Yuya

**Comment by afghankndahiri-byte** [comment]
Hi,
I am running Sacra on some reads corrected using NECAT. The output of NECAT makes the read names as follows with parentheses in them.

ontsa_id_14509_(0_10814_10864_10814_109_22_0.000000)_(469_10822_10140_10864_57_51_46.646883):222-417

On the last step of running SACRA on this data I get the following error.
cns_final.fasta.blasttab.depth.pcratio.faidx.split10.sh: line 1: syntax error near unexpected token (' cns_final.fasta.blasttab.depth.pcratio.faidx.split10.sh: line 1: samtools faidx cns_final.fasta ontsa_id_14509_(0_10814_10864_10814_109_22_0.000000)_(469_10822_10140_10864_57_51_46.646883):222-417 >> cns_final.fasta.blasttab.depth.pcratio.faidx.split10.fasta'

Is there a simple work around to move forward with this or do I need to figure out how to change my read names?

**Comment by yuyanoah** [comment]
Hi,

Yes, we recommend rename your read name.
For instance, the below command is an easy way I can imagine to change your read name.
`sed 's/(/_/g' input.fasta | sed 's/(/_/g' > output.fasta`

Yuya

**Comment by afghankndahiri-byte** [comment]
Termux hecking tootl wi-fi install
